project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: https://github.com/prijall/blog.git
  description: 'My Blogs'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme:  morph
    css: styles.css



